using Eduegate.Frameworks.Attributes;
using System.Runtime.Serialization;

namespace Eduegate.Services.Contracts.Enums.Common
{
    [DataContract(Name = "DynamicLookUpType")]
    public enum DynamicLookUpType
    {
        [EnableCache(true)]
        [EnumMember]
        StudentCategory,
        [EnumMember]
        StudentHouse,
        [EnumMember]
        Section,
        [EnumMember]
        Classes,
        [EnumMember]
        Subject,
        [EnumMember]
        Language,
        [EnumMember]
        SubjectType,
        [EnumMember]
        Cast,
        [EnumMember]
        Relegion,
        [EnumMember]
        Gender,
        [EnumMember]
        BloodGroup,
        [EnumMember]
        GaurdianType,
        [EnumMember]
        FeeDiscount,
        [EnumMember]
        FeeType,
        [EnumMember]
        FeeGroup,
        [EnumMember]
        HostelType,
        [EnumMember]
        Hostel,
        [EnumMember]
        HostelRoom,
        [EnumMember]
        RoomType,
        [EnumMember]
        PresentStatus,
        [EnumMember]
        PresentStaffStatus,
        [EnumMember]
        Student,
        [EnumMember]
        Company,
        [EnumMember]
        VehicleType,
        [EnumMember]
        VehicleOwnershipType,
        [EnumMember]
        BookType,
        [EnumMember]
        BookCondition,
        [EnumMember]
        BookCategory,
        [EnumMember]
        BookStatus,
        [EnumMember]
        School,
        [EnumMember]
        ApplicationStatus,
        [EnumMember]
        AttendenceReason,
        [EnumMember]
        LeaveType,
        [EnumMember]
        LeaveStatus,
        [EnumMember]
        FeePeriod,
        [EnumMember]
        FeeCycle,
        [EnableCache(true)]
        [EnumMember]
        AcademicYear,
        [EnumMember]
        ComponentType,
        [EnumMember]
        LedgerAccount,
        [EnumMember]
        TaxLedgerAccount,
        [EnumMember]
        FeeMaster,
        [EnumMember]
        HolidayList,
        [EnumMember]
        PayrollFrequency,
        [EnumMember]
        PaymentModes,
        [EnumMember]
        SalaryAccount,
        [EnumMember]
        Employee,
        [EnumMember]
        SalaryComponent,
        [EnumMember]
        FeeClasses,
        [EnumMember]
        ClassSection,
        [EnumMember]
        WeekDay,
        [EnumMember]
        ClassTime,
        [EnumMember]
        SalaryStructure,
        [EnumMember]
        TimeTable,
        [EnumMember]
        ExamType,
        [EnumMember]
        VehicleTransmissions,
        [EnumMember]
        VehicleDetails,
        [EnumMember]
        Department,
        [EnumMember]
        LessonPlanStatus,
        [EnumMember]
        AssignmentType,
        [EnumMember]
        AssignmentStatus,
        [EnumMember]
        RouteStopMap,
        [EnumMember]
        RouteType,
        [EnumMember]
        OneSideRouteType,

        [EnumMember]
        SalaryComponents,
        [EnumMember]
        PickupStopMap,
        [EnumMember]
        DropStopMap,
        [EnumMember]
        Route,
        [EnumMember]
        Exams,
        [EnumMember]
        LibraryBooks,
        [EnumMember]
        LibraryBooksCallNo,
        [EnumMember]
        LibraryBooksAccNo,
        [EnumMember]
        LibraryTransactionType,
        [EnumMember]
        LibraryStudentRegisters,
        [EnumMember]
        LibraryStaffRegisters,
        [EnumMember]
        StudentGroup,
        [EnumMember]
        MarkGrade,
        [EnumMember]
        Grade,
        [EnumMember]
        Assignment,
        [EnumMember]
        Countries,
        [EnumMember]
        Syllabus,
        [EnumMember]
        StudentLeaveStatus,
        [EnumMember]
        FeePaymentModes,
        [EnumMember]
        CostCenterDetails,
        [EnumMember]
        BankName,
        [EnumMember]
        AccountPaymentMode,
        [EnumMember]
        TenderType,
        [EnumMember]
        Accounts,
        [EnumMember]
        ParentGroup,
        [EnumMember]
        StudentTransferRequestStatus,
        [EnumMember]
        StudentGroupType,
        [EnumMember]
        Skills,
        [EnumMember]
        SubSkills,
        [EnumMember]
        FineMaster,
        [EnumMember]
        FeeFineType,
        [EnumMember]
        Product,
        [EnumMember]
        BundleProduct,
        [EnumMember]
        Products,
        [EnumMember]
        Task,
        [EnumMember]
        AllEmployee,
        [EnumMember]
        Teacher,
        [EnumMember]
        ProductFamily,
        [EnumMember]
        Brand,
        [EnumMember]
        Unit,
        [EnumMember]
        Categories,
        [EnumMember]
        Rack,
        [EnumMember]
        GuardianType,
        [EnumMember]
        Community,
        [EnumMember]
        Package,
        [EnumMember]
        DocumentStatus,
        [EnumMember]
        FeeStructure,
        [EnumMember]
        VolunteerType,
        [EnumMember]
        TCRequestedStudent,
        [EnumMember]
        Driver,
        [EnumMember]
        VehicleAttender,
        [EnumMember]
        AcademicYearCalendarStatus,
        [EnumMember]
        MainGroup,
        [EnumMember]
        AccountGroup,
        [EnumMember]
        SchoolSyllabus,
        [EnumMember]
        FiscalYear,
        [EnumMember]
        DocumentTypes,
        [EnumMember]
        MainAccountGroup,
        [EnumMember]
        SubAccountGroup,
        [EnumMember]
        AccountSubLedgers,
        [EnumMember]
        PeriodicalTypes,
        [EnumMember]
        AccountIDs,
        [EnumMember]
        AcademicCalendarMaster,
        [EnumMember]
        PropertyType,
        [EnumMember]
        Designation,
        [EnumMember]
        LibraryStudents,
        [EnumMember]
        LibraryStaffs,
        [EnumMember]
        AcademicYearCode,
        [EnumMember]
        ClassTimingSets,
        [EnumMember]
        AcademicYearStatus,
        [EnumMember]
        StudentTransferRequestReasons,
        [EnumMember]
        LeaveSession,
        [EnumMember]
        SubGroup,
        [EnumMember]
        PaymentModesExclude,
        [EnumMember]
        Languages,
        [EnumMember]
        Nationality,
        [EnumMember]
        ApplicationSubmitType,
        [EnumMember]
        LeadType,
        [EnumMember]
        LeadSource,
        [EnumMember]
        CRMRequestType,
        [EnumMember]
        CRMCompany,
        [EnumMember]
        IndustryType,
        [EnumMember]
        MarketSegment,
        [EnumMember]
        LeadStatus,
        [EnumMember]
        CommunicationTypes,
        [EnumMember]
        EmailTemplates,
        [EnumMember]
        AnswerTypes,
        [EnumMember]
        QuestionSelections,
        [EnumMember]
        QuestionGroups,
        [EnumMember]
        OnlineExam,
        [EnumMember]
        OnlineExamStatus,
        [EnumMember]
        OnlineExamOperationStatus,
        [EnumMember]
        FilterClasses,
        [EnumMember]
        ExamGroups,
        [EnumMember]
        ClassTeacher,
        [EnumMember]
        TeachingAids,
        [EnumMember]
        MonthNames,
        [EnumMember]
        LessonPlanTaskTypes,
        [EnumMember]
        CircularTypes,
        [EnumMember]
        CircularPriorities,
        [EnumMember]
        CircularUserTypes,
        [EnumMember]
        CircularStatus,
        [EnumMember]
        AllClass,
        [EnumMember]
        AllSection,
        [EnumMember]
        ClassGroup,
        [EnumMember]
        BreakTypes,
        [EnumMember]
        SkillSets,
        [EnumMember]
        TransportStatus,
        [EnumMember]
        MarkEntryStatus,
        [EnumMember]
        Cashier,
        [EnumMember]
        SecondLanguage,
        [EnumMember]
        ThirdLanguage,
        [EnumMember]
        SubjectMap,
        [EnumMember]
        CreditNoteAccount,
        [EnumMember]
        LicenseType,
        [EnumMember]
        FeeCycleMaster,
        [EnumMember]
        Catogories,
        [EnumMember]
        AllStudents,
        [EnumMember]
        AgendaStatus,
        [EnumMember]
        PresentStatusCode,
        [EnumMember]
        MarkStatuses,
        [EnumMember]
        LanguageType,
        [EnumMember]
        NonFilterClasses,
        [EnumMember]
        NonFilterSections,
        [EnumMember]
        Streams,
        [EnumMember]
        TransportApplicationStatus,
        [EnumMember]
        AllSectionsFilter,
        [EnumMember]
        AdvancedAcademicYear,
        [EnumMember]
        StreamGroups,
        [EnumMember]
        Students,
        [EnumMember]
        PickupStopALL,
        [EnumMember]
        DropStopALL,
        [EnumMember]
        WorkflowEntity,
        [EnumMember]
        WorkFlow,
        [EnumMember]
        WorkflowEntitys,
        [EnumMember]
        MainTeacherClasses,
        [EnumMember]
        MainTeacherSections,
        [EnumMember]
        MainTeacherStudents,
        [EnumMember]
        OnlineExams,
        [EnumMember]
        AcademicYearCalendarEventType,
        [EnumMember]
        Candidate,
        [EnumMember]
        LibraryBookCategoryCode,
        [EnumMember]
        Months,
        [EnumMember]
        Years,
        [EnumMember]
        PreviousClassNames,
        [EnumMember]
        StreamsForApplication,
        [EnumMember]
        SubjectTeacher,
        [EnumMember]
        Variables,
        [EnumMember]
        Operators,
        [EnumMember]
        SalaryComponentGroup,
        [EnumMember]
        Applicant_Student,
        [EnumMember]
        AcademicYearWithLastYear,
        [EnumMember]
        NotificationType,
        [EnumMember]
        NotificationActionType,
        [EnumMember]
        NotificationUser,
        [EnumMember]
        CalendarType,
        [EnumMember]
        NonAcademicCalendarMaster,
        [EnumMember]
        SalaryComponentRelationTypes,
        [EnumMember]
        FullEmployee,
        [EnumMember]
        ReportHeadGroup,
        [EnumMember]
        CalendarMasters,
        [EnumMember]
        StudentList,
        [EnumMember]
        ProductDescription,
        [EnumMember]
        CreditNoteNumbers,
        [EnumMember]
        Currencies,
        [EnumMember]
        AdditionalExpenses,
        [EnumMember]
        MessageSendType,
        [EnumMember]
        UnitGroup,
        [EnumMember]
        ProvisionalAccount,
        [EnumMember]
        TransportStudent,
        [EnumMember]
        TransportStaff,
        [EnumMember]
        SchoolEvents,
        [EnumMember]
        PurchaseCurrency,
        [EnumMember]
        Questions,
        [EnumMember]
        FullAcademicYears,
        [EnumMember]
        InventoryCurrency,
        [EnumMember]
        InvoiceNo,
        [EnumMember]
        LeadNationality,
        [EnumMember]
        DocumentType,
        [EnumMember]
        StudentStatus,
        [EnumMember]
        RouteGroup,
        [EnumMember]
        StudentPickedBy,
        [EnumMember]
        StudentPickupRequestStatus,
        [EnumMember]
        ConcessionApprovalType,
        [EnumMember]
        ConcessionType,
        [EnumMember]
        PromotionStatus,
        [EnumMember]
        ExcludePromotionStatus = 3820,
        [EnumMember]
        AssetAccounts,
        [EnumMember]
        LiabilitiesAccounts,
        [EnumMember]
        EquityAccounts,
        [EnumMember]
        IncomeAccounts,
        [EnumMember]
        ExpensesAccounts,
        [EnumMember]
        Budget,
        [EnumMember]
        ProgressReportPublishStatus,
        [EnumMember]
        FeeConcessionType,
        [EnumMember]
        StockGLAccount,
        [EnumMember]
        ActiveAcademicYear,
        [EnumMember]
        Parent,
        [EnumMember]
        SheduleLogStatus,
        [EnumMember]
        StopEntryStatus,
        [EnumMember]
        ProductName,
        [EnumMember]
        EmployeeLeavingType,
        [EnumMember]
        SponsoredBy,
        [EnumMember]
        SalaryStatus,
        [EnumMember]
        TimesheetEntryStatus,
        [EnumMember]
        TimesheetTimeType,
        [EnumMember]
        TimesheetApprovalStatus,
        [EnumMember]
        EmployeeWB,
        [EnumMember]
        AccomodationType,
        [EnumMember]
        PassageType,
        [EnumMember]
        LeaveGroup,
        [EnumMember]
        LeaveGroupList,
        [EnumMember]
        Allergies,
        [EnumMember]
        OnlineExamResultStatus,
        [EnumMember]
        AssociateTeacher,
        [EnumMember]
        OnlineExamTypes,
        [EnumMember]
        DepartmentsTeacher,
        [EnumMember]
        CandidateStatus,
        [EnumMember]
        ActiveEmployees,
        [EnumMember]
        LessonSubjectKnowledges,
        [EnumMember]
        RatingScales,
        [EnumMember]
        EmployeeGrades,
        [EnumMember]
        ActiveFeeMasters,
        [EnumMember]
        AchievementCategory,
        [EnumMember]
        AchievementType,
        [EnumMember]
        AchievementRanking,
        [EnumMember]
        EmployeeRelationTypes,
        [EnumMember]
        ActiveStudents,
        [EnumMember]
        TicketStatuses,
        [EnumMember]
        TicketPriorities,
        [EnumMember]
        SupportActions,
        [EnumMember]
        TicketReasons,
        [EnumMember]
        SupportAssignedEmployees,
        [EnumMember]
        TicketDocumentTypes,
        [EnumMember]
        BudgetStatuses,
        [EnumMember]
        BudgetTypes,
        [EnumMember]
        BudgetSuggestions,
        [EnumMember]
        SchoolWiseStudents,
        [EnumMember]
        Budgets,
        [EnumMember]
        BudgetGroups,
        [EnumMember]
        Companies,
        [EnumMember]
        FinancialYears,
        [EnumMember]
        Coordinator,
        [EnumMember]
        ProductClassType,
        [EnumMember]
        ClassMapProducts,
        [EnumMember]
        ClassMapFeeMasters,
        [EnumMember]
        StudentPromotionStatuses,
        [EnumMember]
        LoanTypes,
        [EnumMember]
        LoanRequestStatus,
        [EnumMember]
        LoanStatus,
        [EnumMember]
        LoanEntryStatus,
        [EnumMember]
        SignupGroups,
        [EnumMember]
        SignupStatuses,
        [EnumMember]
        SignupCategories,
        [EnumMember]
        SignupTypes,
        [EnumMember]
        SignupSlotTypes,
        [EnumMember]
        SignupSlotMapStatuses,
        [EnumMember]
        ActiveStreams,
        [EnumMember]
        PurchaseRequests,
        [EnumMember]
        Supplier,
        [EnumMember]
        BusinessTypes,
        [EnumMember]
        NonSettledEmployees,
        [EnumMember]
        SupplierContactPersons,
        [EnumMember]
        WeekShortNames,
        [EnumMember]
        Quotations,
        [EnumMember]
        PassageQuestions,
        [EnumMember]
        RFQ,
        [EnumMember]
        Qualifications,
        [EnumMember]
        MeetingRequestStatuses,
        [DataMember]
        SupplierStatuses,
        [DataMember]
        EmployeeStatuses,
        [DataMember]
        CounselorStatuses,
        [EnumMember]
        FilterStudentSettled,
        [EnumMember]
        TenderTypes,
        [EnumMember]
        TenderStatuses,
        [EnumMember]
        Tender,
        [EnumMember]
        LibraryBooksAllAccNo,
        [EnumMember]
        FullStudents,
        [EnumMember]
        ClosedRFQ,
        [EnumMember]
        BankAccounts,
        [EnumMember]
        BidUsers,
        [EnumMember]
        AssetTypes,
        [EnumMember]
        AssetGroups,
        [EnumMember]
        AssetCategories,
        [EnumMember]
        Assets,
        [EnumMember]
        AllAssets,
        [EnumMember]
        TicketEntitilements,
        [EnumMember]
        Airports,
        [EnumMember]
        JobStatus,
        [EnumMember]
        TypeOfJob,
        [EnumMember]
        JobCriteriaTypes,
        [EnumMember]
        FlightClass,
        [EnumMember]
        TicketEntitlementEntryStatus,
        [EnumMember]
        InterviewRounds,
        [EnumMember]
        CustomerAccount,
        [EnumMember]
        FeeCollectScreenStudents,
        [EnumMember]
        Chapters,
        [EnumMember]
        SubjectUnits,
        [EnumMember]
        MaritalStatus,
        [EnumMember]
        AuditData,
        [EnumMember]
        LessonPlanLearningOutcomes,
        [EnumMember]
        LessonPlanLearningObjectives,
        [EnumMember]
        TicketReferenceTypes,
        [EnumMember]
        StaffLedgerAccounts,
        [EnumMember]
        ExpenseLedgerAccounts,
        [EnumMember]
        ProvisionLedgerAccounts,
        [EnumMember]
        ToCampusTransferStudents,
        [EnumMember]
        TicketTypes,
        [EnumMember]
        SupportCategories,
        [EnumMember]
        FacultyTypes,
        [EnumMember]
        JobDescription,
        [EnumMember]
        AvailableJobSkills,
        [EnumMember]
        LogicalOperators,
        [EnumMember]
        TicketDepartments,
        [EnumMember]
        PendingInvoices,
        [EnumMember]
        HM,
        [EnumMember]
        AllAssetCategories,
        [EnumMember]
        AssetProducts,
        [EnumMember]
        TransportCancellationStatuses,
        [EnumMember]
        LiabilityAccounts,
        [EnumMember]
        ExpenseAccounts,
    }
}