namespace Eduegate.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("catalog.ProductInventoryConfig")]
    public partial class ProductInventoryConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductInventoryConfig()
        {
            ProductInventoryConfigCultureDatas = new HashSet<ProductInventoryConfigCultureData>();
            ProductInventoryProductConfigMaps = new HashSet<ProductInventoryProductConfigMap>();
            ProductInventorySKUConfigMaps = new HashSet<ProductInventorySKUConfigMap>();
        }

        [Key]
        public long ProductInventoryConfigIID { get; set; }

        public int? CompanyID { get; set; }

        public decimal? NotifyQuantity { get; set; }

        public decimal? MinimumQuantity { get; set; }

        public decimal? MaximumQuantity { get; set; }

        public decimal? MinimumQuanityInCart { get; set; }

        public decimal? MaximumQuantityInCart { get; set; }

        public bool? IsQuntityUseDecimals { get; set; }

        public byte? BackOrderTypeID { get; set; }

        public byte? IsStockAvailabiltiyID { get; set; }

        [StringLength(50)]
        public string ProductWarranty { get; set; }

        public bool? IsSerialNumber { get; set; }

        public bool? IsSerialRequiredForPurchase { get; set; }

        public short? DeliveryMethod { get; set; }

        public decimal? ProductWeight { get; set; }

        public decimal? ProductLength { get; set; }

        public decimal? ProductWidth { get; set; }

        public decimal? ProductHeight { get; set; }

        public decimal? DimensionalWeight { get; set; }

        public short? PackingTypeID { get; set; }

        public bool? IsMarketPlace { get; set; }

        [StringLength(30)]
        public string HSCode { get; set; }

        public byte? DeliveryDays { get; set; }

        public decimal? ProductCost { get; set; }

        public string Description { get; set; }

        public string Details { get; set; }

        public int? CreatedBy { get; set; }

        public int? UpdatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public DateTime? UpdatedDate { get; set; }

        [Column(TypeName = "timestamp")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [MaxLength(8)]
        public byte[] TimeStamps { get; set; }

        public bool? IsNonRefundable { get; set; }

        [StringLength(200)]
        public string GroupingKey { get; set; }

        public bool? IsSerailNumberAutoGenerated { get; set; }

        public int? MaxQuantityInCartForVerifiedCustomer { get; set; }

        public int? MaxQuantityInCartForNonVerifiedCustomer { get; set; }

        public int? MaxQuantityDuration { get; set; }

        public long? EmployeeID { get; set; }

        public virtual Company Company { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInventoryConfigCultureData> ProductInventoryConfigCultureDatas { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInventoryProductConfigMap> ProductInventoryProductConfigMaps { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInventorySKUConfigMap> ProductInventorySKUConfigMaps { get; set; }
    }
}
