using Eduegate.Framework.Mvc.Attributes;
using Eduegate.Web.Library.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Eduegate.Web.Library.ViewModels.Inventory.Purchase
{
    [ContainerType(Framework.Enums.ContainerTypes.Tab, "", "CRUDModel.Model.DetailViewModel")]
    public class PurchaseQuotationDetailViewModel : BaseMasterViewModel
    {
        public PurchaseQuotationDetailViewModel()
        {
            SKUID = new KeyValueViewModel();
        }

        //[ControlType(Framework.Enums.ControlTypes.CheckBox, "ex-small-col-width", "ng-model='detail.IsRowSelected'")]
        //[CustomDisplay("IsRowSelected")]
        public bool IsRowSelected { get; set; }
        public bool SelectAll { get; set; }
        public long TransactionHead { get; set; }
        public long TransactionDetailID { get; set; }
        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "small-col-width")]
        [CustomDisplay("Sr.No")]
        public long SerialNo { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Select2, "large-col-width detailview-grid")]
        [Select2("SKUID", "String", false,"",optionalAttribute1: "ng-disabled=true")]
        [CustomDisplay("Product")]
        [LazyLoad("", "Catalogs/ProductSKU/ProductSKUSearch", "LookUps.ProductSKUs")]
        [QuickSmartView("Catalogs/ProductSKU", "SKU Details")]
        public KeyValueViewModel SKUID { get; set; }

        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Product Code")]
        public string ProductCode { get; set; }
        public long? ProductID { get; set; }

        public string BarCode { get; set; }
        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label)]
        [CustomDisplay("Description")]
        public string Description { get; set; }


        [Required]
        [RegularExpression("[0-9]{1,}", ErrorMessage = "Invalid format")]
        [ControlType(Framework.Enums.ControlTypes.TextBox, "medium-col-width textright", attribs: "ng-disabled=true")]
        [CustomDisplay("Quantity")]
        public double Quantity { get; set; }

        public long UnitID { get; set; }

        public long UnitGroupID { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "small-col-width")]
        [CustomDisplay("Unit")]
        public string Unit { get; set; }

        [ControlType(Framework.Enums.ControlTypes.Label, "small-col-width")]
        [CustomDisplay("Expected Unit Price")]
        public double UnitPrice { get; set; }

        public bool IsQuantityPopup { get; set; }
        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width textright")]
        [CustomDisplay("Amount")]
        public double Amount { get; set; }

        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay(" ")]
        public string Space1 { get; set; }

        [ControlType(Framework.Enums.ControlTypes.Button, "x-small-col-width", "ng-click='RemoveGridRow($index, CRUDModel.Model.DetailViewModel[0], CRUDModel.Model.DetailViewModel)'")]
        [DisplayName("-")]
        public string Remove { get; set; }

        public bool IsSerialNumberOnPurchase { get; set; }
        public bool IsSerialNumberAutoGenerated { get; set; }
        public string ProductTypeName { get; set; }
        public int ProductLength { get; set; }
        public long BranchID { get; set; }
        public decimal? Fraction { get; set; }
        public decimal? ForeignRate { get; set; } 
    }
}
