using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Eduegate.Domain.Entity.Models
{
    [Table("ProductInventoryConfig", Schema = "catalog")]
    public partial class ProductInventoryConfig
    {
        public ProductInventoryConfig()
        {
            this.ProductInventoryProductConfigMaps = new List<ProductInventoryProductConfigMap>();
            this.ProductInventorySKUConfigMaps = new List<ProductInventorySKUConfigMap>();
            this.ProductInventoryConfigCultureDatas = new List<ProductInventoryConfigCultureData>();
        }

        [Key]
        public long ProductInventoryConfigIID { get; set; }
        public Nullable<decimal> NotifyQuantity { get; set; }
        public Nullable<decimal> MinimumQuantity { get; set; }
        public Nullable<decimal> MaximumQuantity { get; set; }
        public Nullable<decimal> MinimumQuanityInCart { get; set; }
        public Nullable<decimal> MaximumQuantityInCart { get; set; }
        public Nullable<bool> IsQuntityUseDecimals { get; set; }
        public Nullable<byte> BackOrderTypeID { get; set; }
        public Nullable<byte> IsStockAvailabiltiyID { get; set; }
        public string ProductWarranty { get; set; }
        public Nullable<bool> IsSerialNumber { get; set; }
        public Nullable<bool> IsSerialRequiredForPurchase { get; set; }
        public Nullable<short> DeliveryMethod { get; set; }
        public Nullable<decimal> ProductWeight { get; set; }
        public Nullable<decimal> ProductLength { get; set; }
        public Nullable<decimal> ProductWidth { get; set; }
        public Nullable<decimal> ProductHeight { get; set; }
        public Nullable<decimal> DimensionalWeight { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        //public byte[] TimeStamps { get; set; }
        public virtual ICollection<ProductInventoryProductConfigMap> ProductInventoryProductConfigMaps { get; set; }
        public virtual ICollection<ProductInventoryConfigCultureData> ProductInventoryConfigCultureDatas { get; set; }
        public virtual ICollection<ProductInventorySKUConfigMap> ProductInventorySKUConfigMaps { get; set; }
        public Nullable<short>PackingTypeID{ get; set; }
        public Nullable<bool> IsMarketPlace { get; set; }
        public string HSCode { get; set; }
        public Nullable<bool> IsNonRefundable { get; set; }
        public string GroupingKey { get; set; }
        public Nullable<bool> IsSerailNumberAutoGenerated { get; set; }
        public Nullable<int> MaxQuantityInCartForVerifiedCustomer { get; set; }
        public Nullable<int> MaxQuantityInCartForNonVerifiedCustomer { get; set; }
        public Nullable<int> MaxQuantityDuration { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public virtual Company Company { get; set; }
        public Nullable<long> EmployeeID { get; set; }
    }
}
