using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Eduegate.Framework.Mvc.Attributes;
using Eduegate.Web.Library.Common;

namespace Eduegate.Web.Library.ViewModels.Inventory
{
    [ContainerType(Framework.Enums.ContainerTypes.Tab, "", "CRUDModel.Model.DetailViewModel")]
    [DisplayName("Order Details")]
    public class AssetPurchaseOrderDetailViewModel : BaseMasterViewModel
    {
        public AssetPurchaseOrderDetailViewModel()
        {
            IsScreen = "AssetPurchaseOrder";
            Unit = new KeyValueViewModel();
        }

        public long TransactionDetailID { get; set; }

        public long TransactionHead { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "small-col-width")]
        [CustomDisplay("Sr.No")]
        public long SerialNo { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Select2, "large-col-width detailview-grid")]
        [Select2("SKUID", "String", false)]
        [CustomDisplay("Item")]
        [LazyLoad("", "Mutual/GetDynamicLookUpData?lookType=AssetProducts", "LookUps.AssetProducts")]
        public KeyValueViewModel SKUID { get; set; }

        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Item Code")]
        public string ProductCode { get; set; }

        public string PartNo { get; set; }

        public string BarCode { get; set; }
        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "ex-large-col-width")]
        [CustomDisplay("Description")]
        public string Description { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width textright")]
        [CustomDisplay("AvailableQuantity")]
        public double AvailableQuantity { get; set; }

        [Required]
        [RegularExpression("[0-9]{1,}", ErrorMessage = "Invalid format")]
        [ControlType(Framework.Enums.ControlTypes.TextBox, "medium-col-width textright serialnum-wrap ng-change='UpdateDetailGridValues(''@property.Name'', detail, {{$index + 1}})'")]
        [CustomDisplay("Quantity")]
        public double Quantity { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Select2)]
        [Select2("Unit", "Numeric", false, "OnUnitChange(detail)", false, "ng-click=LoadUnit($index)")]
        [CustomDisplay("Unit")]
        [LookUp("LookUps.Unit")]
        public KeyValueViewModel Unit { get; set; }

        [ControlType(Framework.Enums.ControlTypes.Label)]
        [CustomDisplay("Fraction")]
        public double Fraction { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.TextBox, "medium-col-width textright", "ng-blur=GetPurchaseLocalAmount(detail)")]
        [RegularExpression(@"^\d*\.?\d{0,4}$", ErrorMessage = "Please enter a valid amount with up to 4 decimal places")]
        [CustomDisplay("F Rate")]
        public decimal? ForeignRate { get; set; } = 0;

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width textright")]
        [CustomDisplay("L Rate")]
        public double UnitPrice { get; set; }
        public long UnitID { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width textright")]
        [CustomDisplay("F Amount")]
        public decimal? ForeignAmount { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width textright")]
        [CustomDisplay("L Amount")]
        public double Amount { get; set; }

        public bool IsQuantityPopup { get; set; }       

        public int? CostCenterID { get; set; }

        public bool IsSerialNumberOnPurchase { get; set; }
        public bool IsSerialNumberAutoGenerated { get; set; }
        public string ProductTypeName { get; set; }
        public int? ProductLength { get; set; }
        public long? BranchID { get; set; }
        public string IsScreen { get; set; }       
        public decimal? ExchangeRate { get; set; }
        public long? UnitGroupID { get; set; }      
        public List<KeyValueViewModel> UnitDTO { get; set; }
        public List<UnitsViewModel> UnitList { get; set; }
        [ControlType(Framework.Enums.ControlTypes.Button, "x-small-col-width", "ng-click='InsertGridRow($index, ModelStructure.DetailViewModel, CRUDModel.Model.DetailViewModel)'")]
        [DisplayName("+")]
        public string Add { get; set; }

        [ControlType(Framework.Enums.ControlTypes.Button, "x-small-col-width", "ng-click='RemoveGridRow($index, CRUDModel.Model.DetailViewModel[0], CRUDModel.Model.DetailViewModel)'")]
        [DisplayName("-")]
        public string Remove { get; set; }
    }
}
