//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eduegate.ERP.Admin.Reports
{

    //TODO: Reportviewer.aspx.cs not support in .net core, comment codes below
    //public partial class ReportViewer
    //{

    //    /// <summary>
    //    /// form1 control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    //    /// <summary>
    //    /// lblParameterHeading control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.WebControls.Label lblParameterHeading;

    //    /// <summary>
    //    /// reportParameterPanel control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.WebControls.Repeater reportParameterPanel;

    //    /// <summary>
    //    /// btnIssue control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.WebControls.Button btnIssue;

    //    /// <summary>
    //    /// btnView control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.WebControls.Button btnView;

    //    /// <summary>
    //    /// btnPrint control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.WebControls.Button btnPrint;

    //    /// <summary>
    //    /// ScriptManager1 control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.ScriptManager ScriptManager1;

    //    /// <summary>
    //    /// viewer control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::Microsoft.Reporting.WebForms.ReportViewer viewer;

    //    /// <summary>
    //    /// frmPrint control.
    //    /// </summary>
    //    /// <remarks>
    //    /// Auto-generated field.
    //    /// To modify move field declaration from designer file to code-behind file.
    //    /// </remarks>
    //    protected global::System.Web.UI.HtmlControls.HtmlIframe frmPrint;
    //}
}
