using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace Eduegate.Services.Contracts.Enums
{
    [DataContract]
    public enum DynamicViews
    {
        [EnumMember]
        ProductDetails,
        [EnumMember]
        ProductSettings,
        [EnumMember]
        ProductSKUMaps,
        [EnumMember]
        ProductSales,
        [EnumMember]
        ProductPurchase,
        [EnumMember]
        ProductInventory,
        [EnumMember]
        ProductOperations,
        [EnumMember]
        ProductAccounts,
        [EnumMember]
        Brand,
        [EnumMember]
        Category,
        [EnumMember]
        ProductFamily,
        [EnumMember]
        ProductProperty,
        [EnumMember]
        Price,
        [EnumMember]
        PurchaseInvoice,
        [EnumMember]
        PurchaseOrder,
        [EnumMember]
        PurchaseTender,
        [EnumMember]
        PurchaseQuotation,
        [EnumMember]
        PurchaseReturn,
        [EnumMember]
        PurchaseReturnRequest,
        [EnumMember]
        SalesOrder,
        [EnumMember]
        SalesInvoice,
        [EnumMember]
        SalesReturn,
        [EnumMember]
        SalesReturnRequest,
        [EnumMember]
        BranchTransfer,
        [EnumMember]
        BranchTransferRequest,
        [EnumMember]
        DocumentType,
        [EnumMember]
        Customer,
        [EnumMember]
        CustomerGroup,
        [EnumMember]
        Voucher,
        [EnumMember]
        CategorySKUMaps,
        [EnumMember]
        CategoryImageMaps,
        [EnumMember]
        BrandSKUMaps,
        [EnumMember]
        PriceSKUMaps,
        [EnumMember]
        JobEntry,
        [EnumMember]
        ProductSKUDetails,
        [EnumMember]
        PurchaseSKUMaps,
        [EnumMember]
        Supplier,
        [EnumMember]
        JobEntryDetails,
        [EnumMember]
        JobOperation,
        [EnumMember]
        Transaction,
        [EnumMember]
        TicketDetails,
        [EnumMember]
        DeliveryDetails,
        [EnumMember]
        SupportDocumentType,
        [EnumMember]
        Location,
        [EnumMember]
        Basket,
        [EnumMember]
        Vehicle,
        [EnumMember]
        Route,
        [EnumMember]
        City,
        [EnumMember]
        Zone,
        [EnumMember]
        Area,
        [EnumMember]
        DeliverySetting,
        [EnumMember]
        OnlinePayment,
        [EnumMember]
        DeliveryTypes,
        [EnumMember]
        PropertyType,
        [EnumMember]
        ProductTypeDeliveryTypes,
        [EnumMember]
        ProductSKUTypeDeliveryTypes,
        [EnumMember]
        ProductSKUSettings,
        [EnumMember]
        CustomerDeliveryTypes,
        [EnumMember]
        ZoneDeliveryTypes,
        [EnumMember]
        AreaDeliveryTypes,
        [EnumMember]
        ProductSKUPriceSetting,
        [EnumMember]
        DataFeed,
        [EnumMember]
        DataFeedLog,
        [EnumMember]
        BrandPriceSetting,
        [EnumMember]
        CategoryPriceSetting,
        [EnumMember]
        ProductPriceSetting,
        [EnumMember]
        BannerDetails,
        [EnumMember]
        PageDetails,
        [EnumMember]
        PageBoilerplateDetails,
        [EnumMember]
        News,
        [EnumMember]
        Company,
        [EnumMember]
        Department,
        [EnumMember]
        Warehouse,
        [EnumMember]
        BranchGroup,
        [EnumMember]
        Branch,
        [EnumMember]
        Driver,
        [EnumMember]
        LastTransactions,
        [EnumMember]
        BranchWiseInventoryQuantity,
        [EnumMember]
        CartDetails,
        [EnumMember]
        JobComments,
        [EnumMember]
        TransactionCartDetails,
        [EnumMember]
        TransactionComments,
        [EnumMember]
        RepairOrder,
        [EnumMember]
        RepairOrderCustomer,
        [EnumMember]
        RepairOrderDetails,
        [EnumMember]
        VehcileDetails,
        [EnumMember]
        EmailTemplate,
        [EnumMember]
        SKUTagSettings,
        [EnumMember]
        ShoppingCart,
        [EnumMember]
        JobDetails,
        [EnumMember]
        InvoiceDetails,
        [EnumMember]
        InvoiceDeliveryDetails,
        [EnumMember]
        TransactionInvoiceDetails,
        [EnumMember]
        ShoppingCartItems,
        [EnumMember]
        CartDeliveryDetails,
        [EnumMember]
        EmploymentRequest,
        [EnumMember]
        EmploymentAllowances,
        [EnumMember]
        PaymentFort,
        [EnumMember]
        JobEntrySKUDetails,
        [EnumMember]
        JobEntrySIDetails,
        [EnumMember]
        JobEntrySODetails,
        [EnumMember]
        JobEntreyPODetails,
        [EnumMember]
        JobEntryPIDetails,
        [EnumMember]
        JobEntryComments,
        [EnumMember]
        PaymentVoucher,
        [DataMember]
        SupplierTransaction,
        [DataMember]
        PayfortLogs,
        [DataMember]
        Notification,
        [DataMember]
        EmailData,
        [DataMember]
        DayBook,
        [DataMember]
        PaymentKnet,
        [DataMember]
        PayPal,
        [DataMember]
        MasterVisa,
        [DataMember]
        JobProfile,
        [DataMember]
        JobOpening,
        [DataMember]
        ProductSKUBranchSetting,
        [DataMember]
        OrderProcessing,
        [DataMember]
        ClaimDetails,
        [DataMember]
        ClaimSetDetails,
        [DataMember]
        LoginDetails,
        [DataMember]
        ServiceJob,
        [DataMember]
        ModifyShoppingCarts,
        [DataMember]
        TransactionByJob,
        [DataMember]
        SupplierSKU,
        [DataMember]
        ProductSKUTag,
        [DataMember]
        ProductSKUTagMaps,
        [DataMember]
        SalesQuotation,
        [DataMember]
        DeliveryNote,
        [DataMember]
        GoodsReceivedNotes,
        [DataMember]
        GoodsDeliveryNotes,
        [DataMember]
        BundleWrap,
        [DataMember]
        BundleUnWrap,
        [DataMember]
        ServiceEntry,
        [DataMember]
        AssetPurchaseOrder,
    }
}