using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Eduegate.Domain.Entity.CustomEntity
{
    public class ProductSKUDetail
    {
        public long ProductIID { get; set; }
        public long ProductSKUMapIID { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string PartNo { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> SellingQuantityLimit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string ImageFile { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<long> BranchID { get; set; }
        public string LocationName { get; set; }
        public Nullable<long> LocationID { get; set; }
        public string ProductWarranty { get; set; }
        public Nullable<bool> IsSerialNumber { get; set; }
        public Nullable<bool> IsSerialNumberOnPurchase { get; set; }
        public Nullable<bool> IsSerailNumberAutoGenerated { get; set; }
        public Nullable<decimal> ProductLength { get; set; }
        public string ProductTypeName { get; set; }
        public string LocationBarcode { get; set; }
        public string ProductSKUCode { get; set; }
        public string BrandName { get; set; }
        public string BrandCode { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Calorie { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public int? TaxTemplateID { get; set; }
        public int? TaxPercentage { get; set; }
        public bool? HasTaxInclusive { get; set; }
    }
}
