using System;
using System.Runtime.Serialization;

namespace Eduegate.Services.Contracts.Catalog
{
    [DataContract]
    public class POSProductDTO
    {
        [DataMember]
        public long ProductIID { get; set; }
        [DataMember]
        public long ProductSKUMapIID { get; set; }
        [DataMember]
        public Nullable<decimal> ProductPrice { get; set; }
        [DataMember]
        public Nullable<decimal> CostPrice { get; set; }
        [DataMember]
        public Nullable<int> Sequence { get; set; }
        [DataMember]
        public string ProductName { get; set; }
        [DataMember]
        public string Barcode { get; set; }
        [DataMember]
        public string PartNo { get; set; }
      
        [DataMember]
        public string SKU { get; set; }
        [DataMember]
        public Nullable<decimal> SellingQuantityLimit { get; set; }
        [DataMember]
        public Nullable<byte> SortOrder { get; set; }
        [DataMember]
        public Nullable<decimal> Quantity { get; set; }
        [DataMember]
        public string ImageFile { get; set; }
        [DataMember]
        public Nullable<int> CompanyID { get; set; }
        [DataMember]
        public Nullable<long> BranchID { get; set; }
        [DataMember]
        public string LocationName { get; set; }
        [DataMember]
        public Nullable<long> LocationID { get; set; }
        [DataMember]
        public Nullable<DateTime> WarrantyDate { get; set; }
        [DataMember]
        public Nullable<bool> IsSerialNumber { get; set; }
        // Unit price is actually product Price but we need this same name property to use in Sales and Purchase
        [DataMember]
        public Nullable<decimal> UnitPrice { get; set; }
        [DataMember]
        public Nullable<bool> IsSerialNumberOnPurchase { get; set; }
        [DataMember]
        public Nullable<bool> IsSerailNumberAutoGenerated { get; set; }
        [DataMember]
        public string LocationBarcode { get; set; }
        [DataMember]
        public string ProductTypeName { get; set; }
        [DataMember]
        public Nullable<decimal> ProductLength { get; set; }
        [DataMember]
        public Nullable<decimal> Weight { get; set; }
        [DataMember]
        public Nullable<decimal> DeliveryCharge { get; set; }
        [DataMember]
        public Nullable<int> TaxTemplateID { get; set; }
        [DataMember]
        public Nullable<int> TaxPercentage { get; set; }
        [DataMember]
        public Nullable<decimal> TaxAmount { get; set; }
        [DataMember]
        public bool? HasTaxInclusive { get; set; }

        [DataMember]
        public long? PurchaseUnitID { get; set; }

        [DataMember]
        public long? SellingUnitID { get; set; }

        [DataMember]
        public long? PurchaseUnitGroupID { get; set; }

        [DataMember]
        public long? SellingUnitGroupID { get; set; }

        [DataMember]
        public string ProductCode { get; set; }
    }
}