using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntityGenerator.Core.Data
{
    [Keyless]
    public partial class ProductSKUQuantityView
    {
        public int? CompanyID { get; set; }
        public long ProductSKUMapIID { get; set; }
        public long? ProductIID { get; set; }
        public long? BranchID { get; set; }
        [StringLength(500)]
        public string ImageFile { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? ProductPrice { get; set; }
        [StringLength(50)]
        public string Barcode { get; set; }
        [StringLength(50)]
        public string PartNo { get; set; }
        public int? Sequence { get; set; }
        [StringLength(50)]
        public string ProductTypeName { get; set; }
        public int? TaxTemplateID { get; set; }
        public int? TaxPercentage { get; set; }
        [StringLength(50)]
        public string ProductWarranty { get; set; }
        public bool? IsSerialNumber { get; set; }
        public bool? IsSerialNumberOnPurchase { get; set; }
        public bool? IsSerailNumberAutoGenerated { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? ProductLength { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Weight { get; set; }
        [Column(TypeName = "decimal(38, 3)")]
        public decimal Quantity { get; set; }
        [Column(TypeName = "decimal(38, 6)")]
        public decimal CostPrice { get; set; }
        public int? BrandCode { get; set; }
        public int? BrandName { get; set; }
        public int? Calorie { get; set; }
        public int? DeliveryCharge { get; set; }
        public int? HasTaxInclusive { get; set; }
        public int? LocationBarcode { get; set; }
        public int? LocationID { get; set; }
        public int? LocationName { get; set; }
        public int? ProductName { get; set; }
        public int? ProductSKUCode { get; set; }
        public int? SKU { get; set; }
        public int? SellingQuantityLimit { get; set; }
    }
}
