using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntityGenerator.Core.Data
{
    [Keyless]
    public partial class ProductSkuSearchView_OLD
    {
        public long ProductIID { get; set; }
        public long ProductSKUMapIID { get; set; }
        [StringLength(1000)]
        public string SKU { get; set; }
        [StringLength(1000)]
        public string SKUName { get; set; }
        [StringLength(150)]
        public string ProductSKUCode { get; set; }
        [StringLength(50)]
        public string Barcode { get; set; }
        [StringLength(50)]
        public string PartNo { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? productPrice { get; set; }
        [Required]
        [StringLength(150)]
        public string ProductCode { get; set; }
        [Required]
        [StringLength(8)]
        [Unicode(false)]
        public string IsActive { get; set; }
        public string AllProductPrice { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(100)]
        public string CreatedUserName { get; set; }
        [StringLength(100)]
        public string UpdatedUserName { get; set; }
        public int? BranchID { get; set; }
        public int? BrandCode { get; set; }
        public int? BrandName { get; set; }
        public int? Calorie { get; set; }
        public int? CompanyID { get; set; }
        public int? CostPrice { get; set; }
        public int? DeliveryCharge { get; set; }
        public int? HasTaxInclusive { get; set; }
        public int? ImageFile { get; set; }
        public int? IsSerailNumberAutoGenerated { get; set; }
        public int? IsSerialNumber { get; set; }
        public int? IsSerialNumberOnPurchase { get; set; }
        public int? LocationBarcode { get; set; }
        public int? LocationID { get; set; }
        public int? LocationName { get; set; }
        public int? ProductLength { get; set; }
        public int? ProductName { get; set; }
        public int? ProductTypeName { get; set; }
        public int? ProductWarranty { get; set; }
        public int? Quantity { get; set; }
        public int? SellingQuantityLimit { get; set; }
        public int? Sequence { get; set; }
        public int? TaxPercentage { get; set; }
        public int? TaxTemplateID { get; set; }
        public int? Weight { get; set; }
    }
}
