using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Eduegate.Framework.Mvc.Attributes;
using Eduegate.Web.Library.Common;
using Eduegate.Web.Library.ViewModels;

namespace Eduegate.Web.Library.Accounts.Assets
{
    [ContainerType(Framework.Enums.ContainerTypes.Grid, "", "$root.AssetDetailViewModel.TransactionSerialMaps")]
    [Pagination(20, "default")]
    [DisplayName("Serials")]
    public class AssetDepreciationDetailSerialMapViewModel : BaseMasterViewModel
    {
        public AssetDepreciationDetailSerialMapViewModel()
        {
            IsSerialNumberOnAssetEntry = false;
            IsShowDynamicPopup = false;
        }

        public long AssetTransactionSerialMapIID { get; set; }

        public long? TransactionDetailID { get; set; }

        public long? AssetID { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "small-col-width")]
        [CustomDisplay("Sr.No")]
        public long SerialNo { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label)]
        [CustomDisplay("Sequence Code")]
        public string AssetSequenceCode { get; set; }
        public long? AssetSerialMapID { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "small-col-width")]
        [CustomDisplay("Number of Days in the Accounting Period")]
        public int? AccountingPeriodDays { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Dep. Accumulated Till Date")]
        public string AccumulatedTillDateString { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Dep From")]
        public string DepFromDateString { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Dep Till Date")]
        public string DepToDateString { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Dep for the above period")]
        public decimal? DepAbovePeriod { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Dep Booked")]
        public decimal? BookedDepreciation { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Dep Provided till date")]
        public decimal? AccumulatedDepreciationAmount { get; set; }

        [Required]
        [ControlType(Framework.Enums.ControlTypes.Label, "medium-col-width")]
        [CustomDisplay("Net Value")]
        public decimal? NetValue { get; set; }

        public decimal? Quantity { get; set; }

        public decimal? NetAmount { get; set; }

        public decimal? Amount { get; set; }        

        public bool IsShowDynamicPopup { get; set; }

        public bool? IsSerialNumberOnAssetEntry { get; set; }
        public bool? IsSerailNumberAutoGenerated { get; set; }

        public bool? IsRequiredSerialNumber { get; set; }

        public long? AccountID { get; set; }
        public long? AssetGlAccID { get; set; }
        public long? AccumulatedDepGLAccID { get; set; }
        public long? DepreciationExpGLAccID { get; set; }

        public decimal? PreviousAcculatedDepreciationAmount { get; set; }
    }
}